export const ACTION_TYPES={
    ADD_TASK: "ADD_TASK",
    DELETE_TASK: "DELETE_TASK",
    START_EDIT : "START_EDIT",
    UPDATE_TASK:"UPDATE_TASK",
    CANCEL_UPDATE: "CANCEL_UPDATE",
    TOGGLE_TASK: "TOGGLE_TASK",
    SET_TASK_INPUT:"SET_TASK_INPUT",
    START_NEW_DAY: "START_NEW_DAY",
    SET_CARRY_OVER: 'SET_CARRY_OVER',
    SET_EDITING_TEXT: 'SET_EDITING_TEXT'
    
}

export const STORAGE_KEY= 'todoList'