export const ACTION_TYPES={
    ADD_TASK: "ADD_TASK",
    DELETE_TASK: "DELETE_TASK",
    START_EDIT : "START_EDIT",
    UPDATE_TASK:"UPDATE_TASK",
    CANCEL_UPDATE: "CANCEL_UPDATE",
    TOGGLE_TASK: "TOGGLE_TASK"
}